import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import Navbar from "@/components/navbar";
import colors from "@/const/colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-full h-screen overflow-x-hidden text-white"
        style={{ backgroundColor: colors.primary }}
      >
        <main className="flex-1 w-full" style={{ paddingBottom: "62px" }}>
          {children}
        </main>
        <Navbar />
        {/* <Providers>
        </Providers> */}
      </body>
    </html>
  );
}
