import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import Navbar from "@/components/navbar";
import colors from "@/const/colors";
import { HyperLiquidProvider } from "@/providers/hyperliquid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const MAX_WIDTH = "600px";
export const MIN_WIDTH = "320px";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="w-full h-screen overflow-x-hidden text-white"
        style={{
          backgroundColor: colors.primary,
          maxWidth: MAX_WIDTH,
          minWidth: MIN_WIDTH,
        }}
      >
        <main className="flex-1 w-full" style={{ paddingBottom: "62px" }}>
          <Providers>
            <HyperLiquidProvider>{children}</HyperLiquidProvider>
          </Providers>
        </main>
        <Navbar />
      </body>
    </html>
  );
}
