import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/providers";
import AppLayout from "@/components/AppLayout";
import colors from "@/const/colors";
import { HyperLiquidProvider } from "@/providers/hyperliquid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const MAX_WIDTH = "600px";
export const MIN_WIDTH = "320px";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        maxWidth: MAX_WIDTH,
        minWidth: MIN_WIDTH,
        margin: "0 auto",
      }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} w-full h-screen overflow-x-hidden text-white`}
        style={{
          backgroundColor: colors.primary,
        }}
      >
        <Providers>
          <HyperLiquidProvider>
            <AppLayout>{children}</AppLayout>
          </HyperLiquidProvider>
        </Providers>
      </body>
    </html>
  );
}
